name: Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test step
      run: |
        echo "GitHub Actions is working!"
        echo "Current time: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"